### ISSUE TITLE
ORGS is not working

### ISSUE THREAD

**Issue by mkgrei** [githubexporter/github-exporter#80]
https://github.com/infinityworks/github-exporter/blob/284088c21e7d796e9b04674c1e2f00e73d9372e3/config/config.go#L52-L55

The first argument of strings.Split should be `orgs` instead of `repos`.

**Comment by mkgrei** [comment]
https://github.com/infinityworks/github-exporter/pull/75

Should be fixed by the above PR.

**Comment by henrymcconville** [comment]
Fixed in https://github.com/githubexporter/github-exporter/pull/75
